MediaRelease.create!([
  {date: "2021-12-06", title: "Veganuary 2022 - Im Januar mit einer pflanzlichen Ernährung Gutes tun", content: "Zum dritten Mal findet der Veganuary in der Schweiz statt. Heute startet die Kampagne der Veganen Gesellschaft Schweiz. Das Projekt will Menschen motivieren, im Januar während einem Monat die vegane Ernährung auszuprobieren. Unterstützt wird das Ganze von vier prominenten Testimonials.", hyperlink: "https://mailchi.mp/e69e10d95b34/medienmitteilung-veganuary-2022"},
  {date: "2021-09-16", title: "«NoBeef» – Erster veganer Podcast für die Deutschschweiz", content: "Die Vegane Gesellschaft Schweiz lanciert mit «NoBeef» den ersten veganen Podcast speziell für die Deutschschweiz. Er soll informieren und Interessierten den Einstieg in die vegane Lebensweise erleichtern.", hyperlink: "https://mailchi.mp/e9169f0c2e19/medienmitteilung-der-veganen-gesellschaft-schweiz-2061190"},
  {date: "2020-12-08", title: "Veganuary 2021 – Der zweite Veganuary wird noch grösser", content: "Zum zweiten Mal findet der Veganuary in der Schweiz statt. Heute startet die Kampagne der Veganen Gesellschaft Schweiz. Das Projekt will Menschen motivieren, im Januar während einem Monat die vegane Ernährung auszuprobieren. Auch alle grossen Detailhändler machen mit.", hyperlink: "https://mailchi.mp/5b6bc76b6ab1/medienmitteilung-der-veganen-gesellschaft-schweiz-2060910"},
  {date: "2019-12-05", title: "Veganuary 2020 – Veganuary kommt erstmals in die Schweiz", content: "«Probier´s diesen Januar vegan!» ermutigen Influencer*innen, Umweltschützer*innen und Sportler*innen - Veganuary kommt erstmals in die Schweiz", hyperlink: "https://mailchi.mp/1dc319b70c6d/medienmitteilung-der-veganen-gesellschaft-schweiz-1947717"},
  {date: "2020-01-02", title: "Veganuary 2020 – Veganuary motiviert eine Viertel Million Menschen", content: "Seit dem 1. Januar 2020 probieren hierzulande 4’723 Menschen für einen Monat die vegane Ernährung aus. Weltweit sind es gar über 300'000 Menschen. Unterstützt werden sie mit täglichen Tipps und Rezepten via Email. Und zusätzlichen Angeboten in der Gastronomie und Detailhandel.", hyperlink: "https://mailchi.mp/8f8db38841e2/medienmitteilung-der-veganen-gesellschaft-schweiz-1961565"},
  {date: "2020-09-04", title: "Swiss Vegan Awards 2020 – Gleich drei Auszeichnungen für Zürcher Traditionsbäckerei", content: "Bei den Swiss Vegan Awards gab es dieses Jahr eine klare Gewinnerin: Die Bäckerei Sprössling am Schaffhauserplatz in Zürich. Der vegane Sprössling gehört zur Gnädinger Bäckerei, die seit 1942 ebenfalls am Schaffhauserplatz ihre Brötchen backt. Der junge Spross konnte gleich in allen drei Kategorien in den Top 3 mithalten.", hyperlink: "https://mailchi.mp/7a3f1ada27a6/medienmitteilung-der-veganen-gesellschaft-schweiz-2060834"},
  {date: "2021-09-25", title: "Swiss Vegan Awards 2021 – Vegane Innovationen bei den Swiss Vegan Awards", content: "Im Rahmen des Menta Festivals in Bern wurden heute zum 6. Mal die Swiss Vegan Awards vergeben. Die Gewinner*innen überzeugen mit Innovationsgeist und veganen Gaumenfreuden.", hyperlink: "https://mailchi.mp/9156946ff2f1/medienmitteilung-der-veganen-gesellschaft-schweiz-20210925"}
])
